<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

   <!-- 部品の寸法 (Size of Parts in meters) -->

    <xacro:include filename="inertial_macros.xacro"/>
   
<<<<<<< HEAD
    <xacro:property name="chassis_length" value="0.30"/>
    <xacro:property name="chassis_width" value="0.30"/>
    <xacro:property name="chassis_height" value="0.10"/>

    <xacro:property name="chassis_mass" value="1.0"/>

    <xacro:property name="wheel_radius" value="0.1"/>
    <xacro:property name="wheel_thickness" value="0.05"/>
=======
    <xacro:property name="chassis_length" value="0.25"/>
    <xacro:property name="chassis_width" value="0.204"/>
    <xacro:property name="chassis_height" value="0.10"/>

    <xacro:property name="chassis_mass" value="1.5"/>

    <xacro:property name="wheel_radius" value="0.033"/>
    <xacro:property name="wheel_thickness" value="0.026"/>
>>>>>>> acfb3d4 (Fixed Bugs)

    <xacro:property name="wheel_mass" value="0.05"/>

    <xacro:property name="wheel_offset_x" value="0.15"/>
<<<<<<< HEAD
    <xacro:property name="wheel_offset_y" value="${chassis_width/2 + wheel_thickness/2}"/>
    <xacro:property name="wheel_offset_z" value="0"/>

    <xacro:property name="caster_wheel_radius" value="0.05"/>
=======
    <xacro:property name="wheel_offset_y" value="0.105"/>
    <xacro:property name="wheel_offset_z" value="0"/>

    <xacro:property name="caster_wheel_radius" value="0.017"/>
>>>>>>> acfb3d4 (Fixed Bugs)
    <xacro:property name="caster_wheel_mass" value="0.01"/>
    <xacro:property name="caster_wheel_offset_x" value="0.075"/>
    <xacro:property name="caster_wheel_offset_z" value="${wheel_offset_z - wheel_radius + caster_wheel_radius}"/>

    <!-- 素材情報 (Material Information)) -->
    
    <material name="white">
        <color rgba="1 1 1 1"/>
    </material>

    <material name="red">
        <color rgba="1 0 0 1"/>
    </material>


    <material name="blue">
        <color rgba="0.2 0.2 1 1"/>
    </material>


    <!-- ここに図形情報 (Information of Shapes) -->

    <link name="base_link"/>

    <link name="base_footprint"/>

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link"/>
        <child link="base_footprint"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </joint>



    <!-- ボディ (Body) -->

    <link name="chassis">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
            <material name="white"/>
        </visual>

        <collision>
            <origin xyz="0 0 0"/>
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}"/>
            </geometry>
        </collision>

        <xacro:inertial_box mass="0.5" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>


    <!-- 右車輪 (Right Wheel) -->

    <link name="right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <!-- 左車輪 (Left Wheel) -->

    <link name="left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_thickness}"/>
            </geometry>
            <material name="blue"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    
    <!-- 補助輪 (Caster Wheel) -->

    <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="${caster_wheel_mass}" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <!-- ここに関節情報 (Information of Joints) -->

    <joint name="chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
<<<<<<< HEAD
        <origin xyz="0 0 0"/>
=======
        <origin xyz="0 0 ${(chassis_height/2)+0.03}"/>
>>>>>>> acfb3d4 (Fixed Bugs)
    </joint>

    <joint name="right_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="right_wheel"/>
<<<<<<< HEAD
        <origin xyz="0 ${-wheel_offset_y} 0" rpy="${pi/2} 0 0" />
=======
        <origin xyz="0 -0.115 ${wheel_radius}" rpy="${pi/2} 0 0" />
>>>>>>> acfb3d4 (Fixed Bugs)
        <axis xyz="0 0 -1"/>
    </joint>

    <joint name="left_wheel_joint" type="continuous">
        <parent link="base_link"/>
        <child link="left_wheel"/>
<<<<<<< HEAD
        <origin xyz="0 ${wheel_offset_y} 0" rpy="-${pi/2} 0 0" />
=======
        <origin xyz="0 0.115 ${wheel_radius}" rpy="-${pi/2} 0 0" />
>>>>>>> acfb3d4 (Fixed Bugs)
        <axis xyz="0 0 1"/>
    </joint>

    <joint name="caster_wheel_joint" type="fixed">
        <parent link="chassis"/>
        <child link="caster_wheel"/>
<<<<<<< HEAD
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_offset_z}"/>
=======
        <origin xyz="${caster_wheel_offset_x} 0 ${caster_wheel_radius}"/>
>>>>>>> acfb3d4 (Fixed Bugs)
    </joint>


    <gazebo reference="chassis">
        <material>Gazebo/White</material>
    </gazebo>

        <gazebo reference="right_wheel">
        <material>Gazebo/Red</material>
    </gazebo>

    <gazebo reference="left_wheel">
        <material>Gazebo/Red</material>
    </gazebo>

    <gazebo reference="caster_wheel">
        <material>Gazebo/White</material>
        <mu1 value="0.001"/>
        <mu2 value="0.001"/>
    </gazebo>
</robot>
